[build]
builder = "nixpacks"

[build.nixpacksPlan.phases.setup]
aptPkgs = ["proj-bin", "libproj-dev", "proj-data"]

[build.nixpacksPlan.phases.install]
cmds = ["pip install -r requirements.txt"]

[deploy]
startCommand = "gunicorn app:app --bind 0.0.0.0:$PORT"